config/routes.rb
Rails.application.routes.draw do

  # match '/' => redirect('http://store.kiik.com.br'), via: [:get, :post]
  # match '*path' => redirect('http://store.kiik.com.br'), via: [:get, :post]

  # Root Route
  root to: 'pages#home'

  # Admin
  mount Shoppe::Engine => '/admin'

  # Browse Products
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'

  # Order Status
  get 'order/:token' => 'orders#status', as: 'order_status'

  # Basket
  get 'basket' => 'orders#wizard', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  delete 'basket/delete/ajax/:order_item_id' => 'orders#remove_item_ajax', :as => 'remove_basket_item_ajax'

  # Checkout
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/refresh' => 'orders#update_order', :as => 'update_order', :via => [:get, :patch]
  match 'checkout/pay' => 'orders#payment', :as => 'payment', :via => [:get, :patch]
  match 'checkout/pay-now-kiik', to: 'orders#pay_now', as: 'pay_now', via: [:get, :patch]
  match 'checkout/one-click-buy', to: 'orders#one_click_buy', as: 'one-click-buy', via: [:post, :patch]

  match 'checkout/billet' => 'orders#billet', :as => 'billet', :via => [:get, :patch]
  match 'checkout/pay-pal' => 'orders#paypal', :as => 'paypal', :via => [:get, :patch]
  match 'checkout/card-information' => 'orders#card_information', :as => 'card_information', :via => [:get, :patch]
  match 'checkout/redirect-pay-pal' => 'orders#redirect_paypal', :as => 'redirect_paypal', :via => [:get, :patch]

  match 'checkout/finalize' => 'orders#finalize', :as => 'finalize', via: :get
  match 'checkout/finish-order/:id' => 'orders#finish_order', :as => 'finish_order', via: :put

end

app/controllers/orders_controller.rb
# coding: utf-8
require 'httparty'
include ActionView::Helpers::NumberHelper

class OrdersController < ApplicationController
  include ActiveMerchant::Billing
  include PaypalExpressHelper
  include WebsocketRails

  before_action :authenticate

  def show
    @hide_header = true
  end

  def wizard
    @hide_header = true
    unless current_order.order_items.any?
      flash[:notice] = 'Carrinho vazio! (:'
      redirect_to root_path
    end
    payment
  end

  def checkout
    @order = current_order
    @hide_header = true
    if request.patch? #&& @order.proceed_to_confirm(order_params)
      redirect_to checkout_payment_path
    end
  end

  def payment
    @code = create_order(current_order)
  end

  def create_order(order)
    return if order.order_items.empty?
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(order.id)
    items = @order.order_items.map do |item|
      {
        product_description: item.ordered_item.name,
        price_unit: item.ordered_item.price.to_s,
        quant: item.quantity
      }
    end

    header = {
      Accept: 'application/json'
    }

    auth = {
      username: '8210882a5815600efc6090455e3b1178228cebd7',
      password: ''
    }

    body = {
      order: {
        metadata: {
          callback_url: "http://#{request.headers['HTTP_HOST']}/checkout/finish-order",
          items: items
        },
        amount: (items.map { |x| x[:price_unit].to_f * x[:quant]}.sum * 100).to_i,
        company_identifier: "010477",
        order_type: 'physical'
      }
    }
    url = 'https://admin.kiik.com/api/v2/orders'

    response = HTTParty.post(url, header: header, body: body, basic_auth: auth)

    unless response.success?
      flash[:alert] = 'uh oh, houve um erro com a comunicação com o Kiik ):'
      return redirect_to checkout_path
    end
    @order.update(kiik_token: response["order"]["code"])
    session[:kiik_token] = @order.kiik_token
    $redis.set(@order.kiik_token, $redis.get(session[:session_id]))
    response["order"]["code"]
  end

  def billet
    @order = current_order
  end

  def paypal
    @hide_header = true
  end

  def card_information
    @hide_header = true
    @order = current_order
  end

  def redirect_paypal
    @order = current_order

    items = @order.order_items.map do |item|
      {
        name: item.ordered_item.name,
        description: item.ordered_item.description,
        quantity: item.quantity,
        amount: to_cent(item.ordered_item.price),
      }
    end

    response = EXPRESS_GATEWAY.setup_purchase(to_cent(@order.total),
      items: items,
      ip: request.remote_ip,
      return_url: confirmation_url,
      cancel_return_url: catalogue_url,
      brand_name: 'Kiik::Store',
      cart_border_color: '000CD')
    unless response.success?
      flash[:alert] = 'uh oh, houve um erro com a comunicação com o Paypal ):'
      return redirect_to checkout_path
    end

    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end

  def finalize
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(session[:order_id])
    @hide_header = false
    session[:order_id] = nil
    session[:kik_token] = nil
    current_order = nil
    render partial: 'orders/finalize', layout: false
  end

  def finish_order
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_kiik_token(params[:id])
    Shoppe::Country.new(name: 'Brasil').save! unless Shoppe::Country.first

    @payment = OpenStruct.new(params[:order])
    @payment.user = OpenStruct.new(params[:order][:user])
    @payment.address = OpenStruct.new(params[:order][:addresses].first)

    @order.update(
      first_name: @payment.user.name.partition(' ').first,
      last_name: @payment.user.name.partition(' ').last,
      billing_address1: "#{@payment.address.street}, #{@payment.address.number}",
      billing_address2: @payment.address.neighborhood,
      billing_address3: @payment.address.city,
      billing_address4: @payment.address.state,
      billing_postcode: @payment.address.zip,
      billing_country: Shoppe::Country.first,
      email_address: @payment.user.email,
      phone_number: @payment.user.phone,
      status: 'shipped',
      received_at: Time.now,
      accepted_at: Time.now,
      shipped_at: Time.now,
      amount_paid: @payment.amount * 0.01
    )

    Shoppe::Payment.new(
      order_id: @order.id,
      amount: @payment.amount * 0.01,
      reference: rand(0..100000),
      method: 'KiiK'
    ).save

    @payment.amount = number_to_currency(@payment.amount * 0.01, unit: 'R$', separator: ",", delimiter: ".")

    resume_view = render(partial: 'orders/resume', layout: false, formats: [:html])
    WebsocketRails.users[$redis.get(params[:id])].send_message :order_finished, resume_view

    render html: "ok".html_safe
  end

  def remove_item
    current_order_item = Shoppe::OrderItem.find(params[:order_item_id])
    current_order_item.destroy

    return redirect_to basket_path if current_order.order_items.any?
    redirect_to root_path
  end

  def remove_item_ajax
    current_order_item = Shoppe::OrderItem.find(params[:order_item_id])
    current_order_item.destroy
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(current_order.id)
    @code = create_order(@order)
    respond_to do |format|
      format.json { return render(partial: 'orders/pay_now', layout: false, formats: [:html])}
    end
  end

  def destroy
    @current_order.destroy
    session[:order_id] = nil
    redirect_to root_path, notice: 'Basket Empty (:'
  end

  def change_item_quantity
    order_item_id = params['order_item_id']
    quantity = params['quantity']
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(current_order.id)
    order_item = @order.order_items.find(order_item_id)
    order_item.quantity = quantity
    order_item.save!
    order_item = @order.order_items.find(order_item_id)
    item_total = number_to_currency(order_item.ordered_item.price * order_item.quantity, unit: "R$", separator: ",", delimiter: ".")
    total = number_to_currency(order_item.order.total_before_tax, unit: "R$", separator: ",", delimiter: ".")
    @code = create_order(@order)
    @qrcode = RQRCode::QRCode.new(@code)
    qr= ''
    @qrcode.modules.each_index do |x|
      qr+= '<tr>'
      @qrcode.modules.each_index do |y|
        if @qrcode.dark?(x,y)
          qr += '<td class="black"></td>'
        else
          qr += '<td class="white"></td>'
        end
      end
      qr+= '</tr>'
    end
    render json: {item_total: item_total, total: total, code: @code, qr: qr}
  end

  def update_order
  end

  def pay_now
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(current_order.id)
    @code = create_order(@order)
    respond_to do |format|
      format.json { return render(partial: 'orders/pay_now', layout: false, formats: [:html])}
    end
  end

  def one_click_buy
    @product = Shoppe::Product.find_by_permalink!(params['permalink'])
    @order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(current_order.id)
    @order.order_items.add_item(@product, 1)
    @updated_order = Shoppe::Order.includes(order_items: :ordered_item).find_by_id(current_order.id)
    @code = create_order(@updated_order)
    respond_to do |format|
      format.json { return render(partial: 'orders/pay_now', layout: false, formats: [:html])}
    end
  end

  private

  def order_params
    params[:order].permit(
      :first_name,
      :last_name,
      :billing_address1,
      :billing_address2,
      :billing_address3,
      :billing_address4,
      :billing_country_id,
      :billing_postcode,
      :email_address,
      :phone_number
    )
  end

  def create_payment(order)
    544515
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_billet.haml
- @page_title = 'Emitir Boleto!'

.checkout
  %h2 Preenchimento de Cadastro
  %p.intro Preencha os dados para a emissão do Boleto
  %br
  .customer

    .row
      .col-md-6
        %form
          .form-group
            %label{:for => "InputEmail"} Preencha com seu e-mail:
            %input#InputEmail.form-control{:placeholder => "Email", :type => "email"}/
          .form-group
            %label{:for => "InputPassword"} Senha:
            %input#InputPassword.form-control{:placeholder => "Senha", :type => "password"}/
          .form-group
            %label{:for => "InputConfirmPassword"} Confirme sua Senha:
            %input#InputConfirmPassword.form-control{:placeholder => "Confirmar Senha", :type => "password"}/

          .form-group
            %label{:for => "InputName"} Nome:
            %input#InputName.form-control{:placeholder => "Nome", :type => "text"}/

          .form-group
            %label{:for => "InputCPF"} CPF:
            %input#InputCPF.form-control{:placeholder => "CPF", :type => "password"}/

          .form-group
            %label{:for => "InputBirthDate"} Data de Nascimento (dia/mês/ano):
            %input#InputBirthDate.form-control{:placeholder => "Data de Nascimento", :type => "text"}/

          .form-group
            %label{:for => "InputPhone"} Telefone (xx) xxxx-xxxx:
            %input#InputPhone.form-control{:placeholder => "Telefone", :type => "text"}/
      .col-md-6

        %form
          .form-group
            %label{:for => "InputMobile"} Telefone Celular (xx) x-xxxx-xxxx:
            %input#InputMobile.form-control{:placeholder => "Telefone Celular", :type => "text"}/

          .form-group
            %label{:for => "InputStreet"} Endereço de Cobrança:
            %input#InputStreet.form-control{:placeholder => "Endereço", :type => "text"}/

          .form-group
            %label{:for => "InputNumber"} Número:
            %input#InputNumber.form-control{:placeholder => "Número", :type => "text"}/

          .form-group
            %label{:for => "InputApartment"} Complemento:
            %input#InputApartment.form-control{:placeholder => "Complemento", :type => "text"}/

          .form-group
            %label{:for => "InputCity"} Cidade:
            %input#InputCity.form-control{:placeholder => "Cidade", :type => "text"}/

          .form-group
            %label{:for => "InputCountry"} País:
            %input#InputCountry.form-control{:placeholder => "País", :type => "text"}/

          .form-group
            %label{:for => "InputPostalCode"} CEP:
            %input#InputPostalCode.form-control{:placeholder => "CEP", :type => "text"}/

    .row
      .col-md-12
        .form-group
          %label{:for => "InLineRadioOptions"} Sexo:
          %label.radio-inline
            %input#inlineRadio1{:name => "inlineRadioOptions", :type => "radio", :value => "option1"}/
            Masculino
          %label.radio-inline
            %input#inlineRadio1{:name => "inlineRadioOptions", :type => "radio", :value => "option2"}/
            Feminino

        .checkbox
          %label
            %input{:type => "checkbox", :id => "selectado"}/
            Deseja que a entrega seja feita em outro endereço?


  %dl.delivery{:id => "txtHidden"}
    .form-group
      %label{:for => "InputStreet"} Endereço de Entrega:
      %input#InputStreet.form-control{:placeholder => "Endereço", :type => "text"}/

    .form-group
      %label{:for => "InputNumber"} Número:
      %input#InputNumber.form-control{:placeholder => "Número", :type => "text"}/

    .form-group
      %label{:for => "InputApartment"} Complemento:
      %input#InputApartment.form-control{:placeholder => "Complemento", :type => "text"}/

    .form-group
      %label{:for => "InputCity"} Cidade:
      %input#InputCity.form-control{:placeholder => "Cidade", :type => "text"}/

    .form-group
      %label{:for => "InputCountry"} País:
      %input#InputCountry.form-control{:placeholder => "País", :type => "text"}/

    .form-group
      %label{:for => "InputPostalCode"} CEP:
      %input#InputPostalCode.form-control{:placeholder => "CEP", :type => "text"}/

app/views/orders/_card_information.haml
- @page_title = 'Dados do Cartão'

.checkout

  %h2 Preenchimento dos dados do Cartão
  %p.intro Preencha os dados de seu cartão

.row
  .col-md-6
    %form
      .form-group
        %label{:for => "InputEmail"} Preencha com seu e-mail:
        %input#InputEmail.form-control{:placeholder => "Email", :type => "email"}/
      .form-group
        %label{:for => "InputPassword"} Senha:
        %input#InputPassword.form-control{:placeholder => "Senha", :type => "password"}/
      .form-group
        %label{:for => "InputConfirmPassword"} Confirme sua Senha:
        %input#InputConfirmPassword.form-control{:placeholder => "Confirmar Senha", :type => "password"}/

      .form-group
        %label{:for => "InputName"} Nome:
        %input#InputName.form-control{:placeholder => "Nome", :type => "text"}/

      .form-group
        %label{:for => "InputCPF"} CPF:
        %input#InputCPF.form-control{:placeholder => "CPF", :type => "password"}/

      .form-group
        %label{:for => "InputBirthDate"} Data de Nascimento (dia/mês/ano):
        %input#InputBirthDate.form-control{:placeholder => "Data de Nascimento", :type => "text"}/

      .form-group
        %label{:for => "InputPhone"} Telefone (xx) xxxx-xxxx:
        %input#InputPhone.form-control{:placeholder => "Telefone", :type => "text"}/

  .col-md-6
    %form
      .form-group
        %label{:for => "InputMobile"} Telefone Celular (xx) x-xxxx-xxxx:
        %input#InputMobile.form-control{:placeholder => "Telefone Celular", :type => "text"}/

      .form-group
        %label{:for => "InputStreet"} Endereço de Cobrança:
        %input#InputStreet.form-control{:placeholder => "Endereço", :type => "text"}/

      .form-group
        %label{:for => "InputNumber"} Número:
        %input#InputNumber.form-control{:placeholder => "Número", :type => "text"}/

      .form-group
        %label{:for => "InputApartment"} Complemento:
        %input#InputApartment.form-control{:placeholder => "Complemento", :type => "text"}/

      .form-group
        %label{:for => "InputCity"} Cidade:
        %input#InputCity.form-control{:placeholder => "Cidade", :type => "text"}/

      .form-group
        %label{:for => "InputCountry"} País:
        %input#InputCountry.form-control{:placeholder => "País", :type => "text"}/

        .form-group
        %label{:for => "InputPostalCode"} CEP:
        %input#InputPostalCode.form-control{:placeholder => "CEP", :type => "text"}/

.row
  .col-md-12
    %hr
    %form
      .form-group
        %label{:for => "InputCardNumber"} Número do Cartão:
        %input#InputCardNumber.form-control{:placeholder => "Número do Cartão", :type => "text"}/

      .form-group
        %label{:for => "InputName"} Nome impresso no Cartão:
        %input#InputName.form-control{:placeholder => "Nome", :type => "text"}/

      .form-group
        %label{:for => "InputDate"} Validade (mês/ano):
        %input#InputDate.form-control{:placeholder => "Validade", :type => "password"}/

      .form-group
        %label{:for => "InputPassCode"} Insira o Código de Segurança:
        %input#InputPassCode.form-control{:placeholder => "Código de Segurança", :type => "password"}/

app/views/orders/_checkout.html.haml
- @page_title = 'Checkout'

%table.table.table-striped{style: 'table-layout: fixed; width: "100%";'}
  %thead
    %tr
      %td{:align => "center"} KIIK
      %td{:align => "center"} CARTÃO DE CRÉDITO
      %td{:align => "center"} PAYPAL
      %td{:align => "center"} BOLETO BANCÁRIO
  %tbody
    %tr
      %td{:align => "center"}
        = image_tag("kiik-payment.png")
      %td{:align => "center"}
        = image_tag("credit-card.png")
      %td{:align => "center"}
        = image_tag("pay-pal-payment.png")
      %td{:align => "center"}
        = image_tag("billet-payment.png")
    %tr#button_group
      %input#button_value{:name => "button_value", :type => "hidden", :value => ""}/
      %td
        %span.radiobuttons
          %button#button1_button_off.redradio{:name => "button1_button_off", :onclick => "switchON('button_group','button_value','button1',this.value); select_kiik()", :type => "button", :value => "OFF1"}
          %button#button1_button_on.greenradio{:name => "button1_button_on", :style => "display:none;", :type => "button", :value => "ON1"}
      %td
        %span.radiobuttons
          %button#button2_button_off.redradio{:name => "button2_button_off", :onclick => "switchON('button_group','button_value','button2',this.value); select_cards()", :type => "button", :value => "OFF2"}
          %button#button2_button_on.greenradio{:name => "button2_button_on", :style => "display:none;", :type => "button", :value => "ON2"}
      %td
        %span.radiobuttons
          %button#button3_button_off.redradio{:name => "button3_button_off", :onclick => "switchON('button_group','button_value','button3',this.value); select_paypal()", :type => "button", :value => "OFF3"}
          %button#button3_button_on.greenradio{:name => "button3_button_on", :style => "display:none;", :type => "button", :value => "ON3"}
      %td
        %span.radiobuttons
          %button#button4_button_off.redradio{:name => "button4_button_off", :onclick => "switchON('button_group','button_value','button4',this.value); select_billet()", :type => "button", :value => "OFF4"}
          %button#button4_button_on.greenradio{:name => "button4_button_on", :style => "display:none;", :type => "button", :value => "ON4"}

    <!-- %tr -->
    <!--   - for item in current_order.order_items -->
    <!--     %tr -->
    <!--       %td.product -->
    <!--         = item.ordered_item.full_name -->
    <!--       %td.quantity -->
    <!--         %label item.quantity -->
    <!--       %td.money.total -->
    <!--         = number_to_currency item.total -->

app/views/orders/_checkout_sidebar.html.haml
= content_for :sidebar do
  .checkout
    %dl
      %dt Quais pagamentos são aceitos?
      

app/views/orders/_finalize.haml
- @page_title = 'KiiK::Store'
.row
  .col-md-12{style: 'text-align: center'}
    %p.lead{style: 'margin-top: 50px'} Obrigado por testar o Kiik!

%hr

%a.btn.btn-block.btn-primary{ href: 'https://secure.kiik.com.br/', target: '_blank' }
  = fa_icon 'apple'
  Baixe o Kiik aqui!
  = fa_icon 'android'

app/views/orders/_pay_now.haml
.modal.fade.in#pay_now_modal{tabindex: '-1', role: 'dialog', 'aria-labelledby' => 'pay_now_modal_label'}
  .modal-dialog{role: 'document', style: 'width: 800px'}
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal', 'aria-label' => 'Close'}
          %span{'aria-hidden' => true}x
        %h2.modal-title#pay_now_modal_label{style: 'text-align:center'} Pague agora com o KiiK
      .modal-body
        - if @code
          %table.table.table-striped{style: 'table-layout: fixed; width: "100%"'}
            %thead
              %tr
                %td Item
                %td Quantidade
                %td Sub-Total
            %tbody
              - for item in @order.order_items
                %tr
                  %td.product{style: 'width: "33%"'}
                    = item.ordered_item.full_name
                    - unless defined?(readonly)
                      = link_to image_tag("delete.png"), '#', class: 'remove-item btn btn-xs', data: {path: remove_basket_item_ajax_path(item)}
                  %td.quantity{style: 'width: "33%"'}
                    - unless defined?(readonly)
                      %form
                        %input.numItem{:max => "100", :min => "1", :name => "quantity", :type => "number", :value=> item.quantity, data: {item_id: item.id}}
                  %td.money.total{style: 'width: "33%"', id: "money-total-#{item.id}"}= number_to_currency(item.total, unit: "R$", separator: ",", delimiter: ".")
              %tr
                %td
                %td{style: 'color: #f48a21; text-align: right; font-weight: bold'} Total:
                %td#total{style: 'font-weight: bold; color: #f48a21'}
                  = number_to_currency(item.order.total, unit: "R$", separator: ",", delimiter: ".")
            - @qrcode = RQRCode::QRCode.new(@code)
            %table#qrcode-table{style: "margin:auto"}
              - @qrcode.modules.each_index do |x|
                %tr
                  - @qrcode.modules.each_index do |y|
                    - if @qrcode.dark?(x,y)
                      %td.black
                    - else
                      %td.white
            %br
            %p.lead.text-center#code
              = @code
            %p.lead.text-center
              = link_to("Abrir app do KiiK", "kiik://qrcode/#{@code}", class: 'btn btn-warning')
        - else
          %p.lead.text-center Adicione itens ao seu carrinho antes de fazer o pagamento!
:javascript
  $('.remove-item').click(function() {
    return $.ajax({
      url: $(this).data('path'),
      type: 'DELETE',
      dataType: 'html',
      success: function(data) {
        $('#pay_now_modal').modal('hide');
        $('.modal-backdrop.fade.in').hide()
        $('#payment_alert').html(data);
        return $('#pay_now_modal').modal('show');
      },
      error: function(data) {}
    });
  });
  $('.numItem').bind('keyup mouseup', function() {
    input = $(this)[0]
    $.ajax({
      url: '/basket/' + $(input).data('item-id'),
      type: 'POST',
      data: {
        quantity: input.value
      },
      dataType: 'json',
      success: function(data) {
        var id = '#money-total-' + $(input).data('item-id')
        $(id).html(data.item_total);
        $('#total').html(data.total);
        $('#qrcode-table').html(data.qr);
        $('#code').html(data.code);
      },
      error: function(data) {}
    });
  });

app/views/orders/_payment.haml
- require 'rqrcode'
- @page_title = 'Pagar com Kiik'
%input{type: 'hidden', value: @code, id: 'qr_code'}
- @qrcode = RQRCode::QRCode.new(@code)
.row.margin-qrcode
  .col-md-4.col-md-offset-4
    %table#qrcode-table{style: "margin:auto"}
      - @qrcode.modules.each_index do |x|
        %tr
          - @qrcode.modules.each_index do |y|
            - if @qrcode.dark?(x,y)
              %td.black
            - else
              %td.white
    %br
    %p.lead.text-center#code
      = @code
    %p.lead.text-center
      = link_to("Abrir app do KiiK", "kiik://qrcode/#{@code}", class: 'btn btn-warning')

    %p Parabéns por escolher o KiiK. Abra o aplicativo para ler o QR Code e concluir o pagamento de uma forma rápida e segura.
  .col-md-7
    #details
%br
%hr.dash

app/views/orders/_paypal.haml
- @page_title = 'KiiK::Store'

.checkout
  %h2 Você será redirecionado para o Pagamento
  %p.intro Clique na imagem abaixo para ser redirecionado ao pagamento
  %br

  .row
    .col-md-12
      = link_to(image_tag('https://www.paypalobjects.com/webstatic/en_US/i/buttons/buy-logo-large.png'), redirect_paypal_path, target: '_blank')

app/views/orders/_resume.haml
.modal.fade.in#order_resume_modal{tabindex: '-1', role: 'dialog', 'aria-labelledby' => 'order_resume_modal_label'}
  .modal-dialog{role: 'document', style: 'width: 800px'}
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal', 'aria-label' => 'Close'}
          %span{'aria-hidden' => true}x
        %h2.modal-title#order_resume_modal_label{style: 'text-align:center'} Pagamento Efetuado
      .modal-body
        - if @payment.user.avatar != ''
          - avatar = @payment.user.avatar
        - elsif @payment.user.facebook_id != ''
          - avatar = "https://graph.facebook.com/#{@payment.user.facebook_id}/picture?type=large"
        - else
          - avatar = image_url('avatar.png')
        .row{style: 'text-align: center'}
          .col-md-12
            %img.circular{src: avatar}
            %h2{style: 'color: #f48a21'}= @payment.user.name
            %h4
              Seu Pagamento de
              %large= @payment.amount
              foi efetuado com sucesso!
        .row
          .col-md-12{style: 'text-align: center; margin-top: 50px'}
            %h3 Detalhes do Pedido
        .row{style: 'margin-top: 30px'}
          .col-md-12
            %h5 Produtos
            %table.table.table-striped{style: 'table-layout: fixed; width: "100%"'}
              %thead
                %tr
                  %td Item
                  %td Quantidade
                  %td Sub-Total
              %tbody
                - if @order
                  - for item in @order.order_items
                    %tr
                      %td.product{style: 'width: "33%"'}
                        = item.ordered_item.full_name
                      %td.quantity{style: 'width: "33%"'}
                        = item.quantity
                      %td.money.total{style: 'width: "33%"'}= number_to_currency item.total
                  %tr
                    %td
                    %td{style: 'color: #f48a21; text-align: right; font-weight: bold'} Total:
                    %td#total{style: 'font-weight: bold; color: #f48a21'}
                      = number_to_currency(item.order.total, unit: "R$", separator: ",", delimiter: ".")
        .row
          - if @order
            .col-md-12
              %h5 Endereço de Entrega
              .col-md-3
                %p{style: 'font-weight: bold'} Rua
                %p= @order.billing_address1
              .col-md-2
                %p{style: 'font-weight: bold'} Bairro
                %p= @order.billing_address2
              .col-md-3
                %p{style: 'font-weight: bold'} Cidade
                %p= @order.billing_address3
              .col-md-2
                %p{style: 'font-weight: bold'} Estado
                %p=@order.billing_address4
              .col-md-2
                %p{style: 'font-weight: bold'} CEP
                %p= @order.billing_postcode

app/views/orders/_show.html.haml
- @page_title = 'Your Shopping Bag'
.checkout
  = render 'shared/order_items', :order => current_order

%hr.dash
.col-md-offset-4
  %a.btn.btn-primary{href: '#payment-types'} ESCOLHER FORMA DE PAGAMENTO